"""Replace superseded concept records with reference-directed Blender design contracts."""
import json, shutil
from pathlib import Path
P=Path(__file__).resolve().parent
old=P/'previous-concept';old.mkdir(exist_ok=True)
for name in ['room-brief.json','room-layout.json','props.json','openings.json','plan-metadata.json','milestone-reviews.json','final-report.json','review.html']:
 if not (old/name).exists():shutil.copy2(P/name,old/name)
def rd(n):return json.loads((P/n).read_text())
def wr(n,x):(P/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
b=rd('room-brief.json');b['boundsMeters']=[11,3.8,13.8];b['purpose']='按用户提供的四视角二次元咖啡馆参考图，精细建模独立场景；中央为数字人表演与对话区域。';b['circulation']={'description':'西侧 2.4m 双扇玻璃入口到中央留白，后方吧台；右后真实拱门通往纵深座位区。','minimumClearanceMeters':1.2};b['productionCamera']={'viewport':[1600,1000],'location':[0,1.42,1.58],'target':[0,1.395,0],'verticalFovDegrees':24};b['performanceBudget']['maxSceneTriangles']=350000
b['styleReference']={'source':'reference/user-cafe.png','direction':'用户四视角参考：浅木拼板吧台、金属玻璃甜点柜、专业双头咖啡机、密集层架与垂挂植物、深木落地窗、青绿色软包与日光窗影。','authoringMethod':'local Blender modelling; physically lit illustrative materials'}
b['artifacts'].update(floorPlan='plans/blender-lower-room.png',reflectedCeilingPlan='plans/blender-reflected-ceiling.png',visualTarget='renders/blender-main.png',wallElevations=['renders/blender-counter.png'],openingContactSheet='masks/authored-contact-sheet.png')
b['productionSource']='blender/tide-cafe.blend';b['performanceBudgetNote']='Review context is included in source; actual runtime tier and draw-call budgets remain unverified.';wr('room-brief.json',b)
ops=rd('openings.json');ops['primaryArrival']={'openingId':'entry','exception':''};ops['openings']=[]
for id,kind,wall,c,w,h,s,dest in [('entry','door','west window wall',[-5.6,-1.9,1.625],2.4,3.25,0,'visible outdoor terrace'),('window-1','window','west window wall',[-5.6,-4.15,1.875],1.6,3.05,.35,'coastal terrace, trees, sky and far town'),('window-2','window','west window wall',[-5.6,.8,1.875],2.6,3.05,.35,'coastal terrace and trees'),('window-3','window','west window wall',[-5.6,3.5,1.875],2.2,3.05,.35,'coastal terrace and trees'),('rear-seat-arch','door','back wall with true arch',[3.85,4.92,1.575],1.86,3.15,0,'3.7m-deep second seating room; sightline to actual rear window'),('nook-window','window','nook rear wall',[4,8.62,1.9],2.3,2.6,.60,'sky and outdoor context')]:
 ops['openings'].append(dict(id=id,kind=kind,wallId=wall,centerBlenderMeters=c,widthMeters=w,heightMeters=h,sillMeters=s,thresholdMeters=0,depthMeters=.24,destination=dest,mask=f'masks/authored-{id}.png',cutter=f'masks/authored-{id}.json',approved=False,shape='round-head arch' if id=='rear-seat-arch' else 'rectangle',boolean='applied Exact in Blender'))
wr('openings.json',ops)
l=rd('room-layout.json');l['surfaces']=[{'id':n,'blenderObject':n} for n in ['structural floor','sealed main ceiling','west window wall','east wall','back wall with true arch','front return wall','nook floor','nook ceiling','nook west wall','nook east wall','nook rear wall']];l['instances']=[];l['source']='blender/tide-cafe.blend';l['evaluatedGeometryAudit']='blender/geometry-audit.json';l['coordinateConvention']='Blender Z up; Three.js x=X, y=Z, z=-Y';l['productionCamera']=b['productionCamera'];l.pop('conceptGeometry',None)
pr=rd('props.json');pr['assets']=[]
for id,desc,dim,front,face,cls,count,poly in [('counter','浅橡木逐块拼板吧台、石材台面、踢脚与木钉',[7.45,1.093,1.16],'positive-z','floor','hero',1,20000),('pastry-case','金属边框、玻璃层板、倾斜前玻璃、十八份真实甜点',[2.45,.83,.83],'positive-z','freestanding','hero',1,12000),('espresso','精细双头咖啡机、开放杯槽、压力表刻度、冲煮头、木手柄、格栅滴水盘',[1.15,.72,.67],'positive-z','freestanding','hero',1,10000),('table','方形木桌，围板榫接、四腿与布桌旗',[1.12,.805,.82],'positive-y','floor','reusable',5,1600),('chair','木质椅子、真实框架、青绿坐垫',[.5,1.0,.55],'positive-z','floor','reusable',10,1800),('pendant','双层旋压金属灯罩、扩散板、吊线、灯座',[.58,.9,.58],'negative-y','ceiling','reusable',5,2200),('greenery','陶盆、土壤、真实分枝、光滑弯曲叶片与垂挂藤蔓',[.65,1.3,.65],'positive-z','floor','reusable',17,12000),('banquette','靠墙长卡座、独立软包、滚边缝与亚麻靠垫',[.85,1.315,5.1],'negative-x','floor','hero',1,8000)]:
 pr['assets'].append({'id':id,'function':desc,'description':desc,'dimensionsMeters':dim,'semanticFront':front,'attachmentFace':face,'class':cls,'targetPolycount':poly,'intendedInstances':count,'rejectionCriteria':['可见悬空、穿插或错误支撑','与参考图的结构和材质语义明显不一致','抢占中央数字人区域'],'image':{'prompt':'用户提供的多视角精细二次元咖啡馆参考图','generator':'user-supplied reference','source':'reference/user-cafe.png','approved':False,'approvedBy':''},'production':{'method':'Blender authored geometry','source':'blender/tide-cafe.blend','thirdPartyGeneration':False}})
 for i in range(count):l['instances'].append({'id':f'{id}-{i}','assetId':id,'source':'blender/tide-cafe.blend','placementAuthority':'blender/geometry-audit.json'})
wr('props.json',pr);wr('room-layout.json',l)
plan=rd('plan-metadata.json');plan['geometrySource']='blender/tide-cafe.blend';plan['projectionSource']='actual-meshes';plan.pop('features',None);plan['geometryAudit']='blender/geometry-audit.json';plan['notes']={'planScope':'orthographic projections of actual evaluated authored Blender scene','layoutCoordinates':'Blender Z up','barriers':'sealed 0.24m thick substrates with six applied Exact Booleans','columns':'timber wall posts, no false open colonnades','circulation':'2.4m glazed western arrival, central reserved character area, right rear seating passage','heroReserve':'x/y ±1.2m'};wr('plan-metadata.json',plan)
r=rd('milestone-reviews.json');r['function']['status']='pending';r['function']['notes']='用户否决初版草模，并明确提供参考图要求使用 Blender 精细建模。本轮建模由该明确指令授权；没有将此指令伪记为 Function 门槛全项批准。';r['function']['evidence']=['reference/user-cafe.png','blender/authoring-metadata.json'];r['form'].update(status='pending',evidence=['blender/tide-cafe.blend','renders/blender-main.png','renders/blender-window-seating.png','renders/blender-counter.png','renders/blender-depth.png','blender/geometry-audit.json'],strangestElement='拱门承诺可穿越，已切开结构墙并连接真实纵深座位区；窗景来自三维室外几何。',notes='等待用户审阅实际 Blender 渲染；尚未导出 runtime GLB。')
wr('milestone-reviews.json',r)
f=rd('final-report.json');f['gates']={'function':False,'form':False,'runtime':False};f['designVerification']={'authoringTool':'Blender 5.2.2 LTS','reference':'reference/user-cafe.png','source':'blender/tide-cafe.blend','meshEvidence':'blender/geometry-audit.json','runtimeIntegrated':False};f['postmortem']={'observations':['用户要求的细节不能由简单几何草模证明；本轮以真实 Blender 建模和实际渲染为证据。'],'corrections':['修复拱形 Boolean 切割体法线，确保真实通道。','让薄玻璃透过阴影射线，保留窗框日光阴影。','将简单咖啡机换为精细单独建模的双头机器。'],'remainingRisks':['Function/Form human review pending','Runtime camera fit, collision, texture tiers and draw-call budgets unverified','Skill validator mandates positive Meshy budget but project remains local modelling with zero spend']};wr('final-report.json',f)
(P/'README.md').write_text('''# 潮汐咖啡馆 · 参考图精细建模\n\n用户明确要求参照 `reference/user-cafe.png` 改用 Blender 精细建模。上一版草模不作为最终成果，原记录存入 `previous-concept/`。\n\n## 实际成果\n\n- 可编辑、已打包纹理的源文件：`blender/tide-cafe.blend`。\n- 建模脚本：项目根目录 `scripts/blender/anime_cafe_room.py`。\n- 实际主图、窗边座位、收银台、纵深座位区：`renders/blender-*.png`。\n- 几何审计：`blender/geometry-audit.json`，含真实结构开口与逐对象评估三角形数量。\n- 生成记录、机位与同源灯具清单：`blender/authoring-metadata.json`。\n- 参考图和本地制作的菜单、植物装饰画保存在包内。\n\n## 重建\n\n```sh\n/Applications/Blender.app/Contents/MacOS/Blender -b --factory-startup -P scripts/blender/anime_cafe_room.py -- --one main\n```\n\n完整四机位省略 `--one main`。`--quick` 用于迭代检查。`--all` 增加四角、三天花视角与真实舞台机位。\n\n用 `blender/render_reviews.py` 从保存的 `.blend` 渲染任意命名机位，不需重新生成几何。`blender/audit_source.py` 评估最终网格与开口。\n\n## 当前阶段\n\n本轮是用户明确授权的参考图精细建模修订。Function/Form 保持待审阅，未伪造批准。尚未导出运行时 GLB、改动背景选择器或部署。预算为零，全部本地建模。技能通用验证器的强制 Meshy 预算字段与此方案冲突，如实保留校验失败。\n''')
print('reference-directed authored design records saved')
